import Head from "next/head";
import Sidebar from "@/components/Sidebar/sidebar";
import styles from "src/styles/Snapshots.module.css";

export default function Snapshots() {
  return (
    <>
      <Head>
        <title>Snapshots - LINKED DAO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
        <link rel="icon" href="/logo.svg" />
      </Head>
      <main className={styles.main}>
        <Sidebar />
        <div className={styles.div}></div>
        <form className={styles.form}>
          <div className={styles.field}>
            <label>Snap Token</label>
            <input type="text" placeholder="Enter Contact Address" required />
          </div>
          <div className={styles.field}>
            <label>Air drop Token</label>
            <input type="text" placeholder="Enter Contact Address" required />
          </div>
          <button disabled className={styles.btn}>
            Run Snapshot
          </button>
        </form>
      </main>
    </>
  );
}
